version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 6666:80
    networks:
      - backend
      - frontend

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    networks:
      - backend

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    networks:
      - backend

  phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    links:
      - "mysql:test"
    ports:
      - 6001:80
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
