version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - php
    volumes:
      - ./php/:/var/www/html/
    ports:
      - 6666:80
    networks:
      - backend
      - frontend

  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    expose:
      - 9000
    volumes:
      - ./php/:/var/www/html/
    networks:
      - backend

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    networks:
      - backend

  phpmyadmin:
    container_name: phpmyadmin
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    links:
      - "mysql:test"
    ports:
      - 6001:80
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
